controller_list:
  - name: fake_lwa4p_arm_controller
    type: $(arg execution_type)
    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint
initial:  # Define initial robot poses.
  - group: lwa4p_arm
    pose: Home